#!/usr/bin/env bash
# This script will copy a file from local to server

if [ "$#" -ge 2 ]
then
    scp -i "$4" "$1" "$3"@"$2":~/
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
