#!/usr/bin/env bash
# This file will write the command to install nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw --force enable
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo service start nginx
