#!/usr/bin/env bash
# This script will redirect /redirect_me
sudo sed -i -e "s+location / {+location /redirect_me {\n\t\treturn 301 "https://www.youtube.com/watch?v=QH2-TGUlwu4" ;+g" /etc/nginx/sites-available/default
sudo service nginx restart
