#!/usr/bin/env bash
# This script will redirect /redirect_me
sudo sed -i -e "s+server_name _;+server_name 34.148.148.119;\n\n\tlocation /redirect_me {\n\t\treturn 301 "https://www.youtube.com/watch?v=QH2-TGUlwu4" ;\n\t}\n+g" /etc/nginx/sites-available/default
sudo service nginx restart
