#!/usr/bin/env bash
# This script will configure HAPROXY load balancer
sudo apt-get update
sudo apt-get -y install haproxy
sudo sed -i -e "s+504.http+504.http\n\nfrontend web-frontend\n\tbind *:80\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver web-server1 34.148.148.119:80 check\n\tserver web-server2 44.200.78.83:80 check\n+" /etc/haproxy/haproxy.cfg
sudo sed -i -e "s+16\"+16\"\nENABLED=1\n+" /etc/default/haproxy
sudo service haproxy restart
