#!/usr/bin/env bash
#This scripts displays To infinity and beyond indefinitely With a sleep 2 in
#between each iteration and I am invincible!!! when receiving a SIGTERM signal
word='To infinity and beyond'
trap "{ echo 'I am invincible!!!'; }" SIGTERM
while true
do
    echo "$word"
    sleep 2
done
