#!/usr/bin/env bash
#This script will print numbers from 1 to 100,
#if number is multiple of 3 then it will print fizz
#if number is multiple of 5 then it will print Buzz
#if number is multiple of 15 the it will print fizzbuzz
i=1
while [ $i -le 100 ]
do
    if [ $((i % 3)) -eq 0 ] && [ ! $((i % 15)) -eq 0 ]
    then
        echo Fizz
    elif [ $((i % 5)) -eq 0 ] && [ ! $((i % 15)) -eq 0 ]
    then
        echo Buzz
    elif [ $((i % 15)) -eq 0 ]
    then
        echo FizzBuzz
    else
        echo "$i"
    fi
    ((i++))
done
