#!/usr/bin/env bash
#This script is used to cut lines into words
FILE="/etc/passwd"
while IFS=: read -r username password userid groupid comment homedir cmdshell
do
    echo "$username:$userid:$homedir"
done < $FILE
