#!/usr/bin/env bash
#This script will write badluck on the 4th iteration
#and goodluck on 8th iteration the rest will be Best school
names='Best School'
i=1
while [ $i -le 10 ]
do
   if [ $i -eq 4 ]
   then
       echo "bad luck"
   elif [ $i -eq 8 ]
   then
       echo "good luck"
   else
       echo "$names"
   fi
   ((i++))
done
