#!/usr/bin/env bash
#This script will work on the file
FILE=./school
if [ -e "$FILE" ]
then
    echo school file exists
    if [ -s "$FILE" ]
    then
        echo school is not empty
    else
        echo school is empty
    fi
    if [ -f "$FILE" ]
    then
        echo school is a regular file
    fi
else
    echo school file does not exist
fi
