#!/usr/bin/env bash
# This script will setup a firewall in the first server
sudo apt update
sudo apt install ufw
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
sudo service ufw restart
